DROP TABLE TB_ENDERECO;

CREATE TABLE TB_ENDERECO (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  RUA VARCHAR(100) NOT NULL,
  NUMERO VARCHAR(10) NOT NULL,
  COMPLEMENTO VARCHAR(100) NOT NULL,
  BAIRRO VARCHAR(100) UNIQUE NOT NULL,
  CIDADE VARCHAR(100) NOT NULL,
  ESTADO VARCHAR(20) NOT NULL,
  PAIS VARCHAR(100) NOT NULL,
  CEP VARCHAR(10) NOT NULL,
  LATITUDE DOUBLE PRECISION NOT NULL,
  LONGITUDE DOUBLE PRECISION NOT NULL,
  PRIMARY KEY (ID)
);

INSERT INTO TB_ENDERECO(RUA, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, PAIS, CEP, LATITUDE, LONGITUDE)
values ('Rua Nova Paulina', '45A', 'Casa 1', 'Jardim Colibri', 'Embu das Artes', 'São Paulo - SP', 'Brasil', '06822-890', 3.000000, 4.000000);

INSERT INTO TB_ENDERECO(RUA, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, PAIS, CEP, LATITUDE, LONGITUDE)
values ('Rua Dr. Joanopolis', '130', 'Apartamento 2', 'Jardim Coelba', 'Itapecerica da Serra', 'São Paulo - SP', 'Brasil', '00022-890', 1.000999, 2.000000);

INSERT INTO TB_ENDERECO(RUA, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, PAIS, CEP, LATITUDE, LONGITUDE)
values ('Rua Da Maça', '100', 'Casa 1', 'Jardim Santo Antonio', 'Curitiba', 'Paraná - PR', 'Brasil', '99922-890', 2.000000, 2.000999);
